language: python
dist: latest

python:
  - 3.5

env:
  - TOXENV=django111-drf39
  - TOXENV=django111-drf310
  - TOXENV=django111-drflatest
  - TOXENV=django20-drf39
  - TOXENV=django20-drf310
  - TOXENV=django20-drflatest
  - TOXENV=django21-drf39
  - TOXENV=django21-drf310
  - TOXENV=django21-drflatest
  - TOXENV=django22-drf39
  - TOXENV=django22-drf310
  - TOXENV=django22-drflatest

matrix:
  include:
    - python: 3.5
      env: TOXENV=quality
    - python: 3.5
      env: TOXENV=docs

install:
  - pip install -r requirements/test.txt
  - python setup.py install
  - pip install coveralls
script:
  - tox
after_success: 
  - codecov
  
# Set password via "travis encrypt --add deploy.password"; for details, see
# https://docs.travis-ci.com/user/deployment/pypi
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  password:
    secure: BlYK3lplRoPiNfzqslxyReJZrC1QUT9Ls1A1xIxc3IHxKl9WEkqC2xO5vBvQDFKtMyooq8bGeN/gfksaZpRYqBmrO7hPITiz0FH0wPFdjoIikI4NTqKVxjhqUho0ZWmpxNXrX/iMd9Y2R4uZRXZGaWaTSRHfF9fPVlkbo66s7vw=
  on:
    tags: true
    python: 3.5
    condition: "$TOXENV = django111-drflatest"
